#!/bin/bash
. ./.env
set -e

# Create a replication role
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE $REPLICATOR_USER WITH REPLICATION PASSWORD '$REPLICATOR_PASSWORD' LOGIN;
  CREATE PUBLICATION $POSTGRES_PUBLICATION_NAME FOR ALL TABLES;
EOSQL