services:
  postgres1:
    image: postgres:latest
    container_name: postgres1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data
      - ./init-postgres1.sh:/docker-entrypoint-initdb.d/init-postgres1.sh:ro
      - ./.env:/docker-entrypoint-initdb.d/.env:ro
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=5
               -c max_wal_senders=5
               -c listen_addresses='*'
    networks:
      - replication_network

  postgres2:
    image: postgres:latest
    container_name: postgres2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data
      - ./init-postgres2.sh:/docker-entrypoint-initdb.d/init-postgres2.sh:ro
      - ./.env:/docker-entrypoint-initdb.d/.env:ro
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=5
               -c max_wal_senders=5
               -c listen_addresses='*'
    networks:
      - replication_network

  pooler:
    image: bitnami/pgpool:latest
    container_name: pgpool
    environment:
      PGPOOL_BACKEND_NODES: "0:postgres1:5432,1:postgres2:5432"
      PGPOOL_SR_CHECK_USER: ${POSTGRES_USER}
      PGPOOL_SR_CHECK_PASSWORD: ${POSTGRES_PASSWORD}
      PGPOOL_POSTGRES_USERNAME: ${POSTGRES_USER}
      PGPOOL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPOOL_ADMIN_USERNAME: ${PGPOOL_ADMIN_USERNAME}
      PGPOOL_ADMIN_PASSWORD: ${PGPOOL_ADMIN_PASSWORD}
    ports:
      - "5434:5432" # Connect to pgpool:5434
    networks:
      - replication_network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - replication_network

volumes:
  postgres1_data:
  postgres2_data:
  pgadmin-data:

networks:
  replication_network:
    driver: bridge
